### ISSUE TITLE
请问一下有托管到maven库里面吗，以及有没有sdk最低版本限制？

### ISSUE THREAD

**Issue by WayneLyn** [dersoncheng/MultipleTheme#3]

**Comment by dersoncheng** [comment]
暂时没有托管到meaven上？现在的代码因为用到了属性动画，所以要保留属性动画的话sdk最低限制应该是3.0或以上，当然你也可以用开源的nine9android来做切换夜间模式时的属性动画，这样就不会有sdk版本的限制了
